### ISSUE TITLE
Make PocoVM available on Github pages

### ISSUE THREAD

**Issue by park-brian** [gmisail64/PocoVM#2]
It looks like you can just create the gh-pages branch off master, or even use gh-pages as the primary branch.

**Comment by gmisail** [comment]
[It is available here.](https://gmisail64.github.io/PocoVM/)

**Comment by park-brian** [comment]
Whoops! thanks :)

**Comment by gmisail** [comment]
I probably should've put it on the README, thats my bad! I'll add it now
